name: Generate and publish documentation on main push

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build-on-tag:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'generate_docs')
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.15
        
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run generate-docs

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
